Repository PrestaShopCorp/puik, pull requests merged in 2023-06, with the labels that each got.

#136 fix: icon alignement in button
  packages/theme/src/button.scss
  packages/theme/src/common/typography.scss
Labels: waiting for UX, waiting for dev

#95 [Feature]: Menu component
  .gitignore
  packages/components/index.ts
  packages/components/menu-item-separator/style/css.ts
  packages/components/menu-item-separator/style/index.ts
  packages/components/menu-item-title/style/css.ts
  packages/components/menu-item-title/style/index.ts
  packages/components/menu-item/style/css.ts
  packages/components/menu-item/style/index.ts
  packages/components/menu/index.ts
  packages/components/menu/src/menu-item-separator.ts
  packages/components/menu/src/menu-item-separator.vue
  packages/components/menu/src/menu-item-title.ts
  packages/components/menu/src/menu-item-title.vue
  packages/components/menu/src/menu-item.ts
  packages/components/menu/src/menu-item.vue
  packages/components/menu/src/menu.ts
  packages/components/menu/src/menu.vue
  packages/components/menu/stories/menu.stories.ts
  packages/components/menu/style/css.ts
  packages/components/menu/style/index.ts
  packages/components/menu/test/menu-item-separator.spec.ts
  packages/components/menu/test/menu-item.spec.ts
  packages/components/menu/test/menu.spec.ts
  packages/puik/component.ts
  packages/theme/src/index.scss
  packages/theme/src/menu-item-separator.scss
  packages/theme/src/menu-item-title.scss
  packages/theme/src/menu-item.scss
  packages/theme/src/menu.scss
  playground/src/App.vue
  typings/global.d.ts
Labels: Feature

#132 [Feature]: Create issue design template
  .github/ISSUE_TEMPLATE/---design.md
  .github/ISSUE_TEMPLATE/Design Issue.yml
Labels: Feature

#107 [Feature]: Skeleton loader component
  packages/components/index.ts
  packages/components/skeleton-loader-group/style/css.ts
  packages/components/skeleton-loader-group/style/index.ts
  packages/components/skeleton-loader/index.ts
  packages/components/skeleton-loader/src/skeleton-loader-group.ts
  packages/components/skeleton-loader/src/skeleton-loader-group.vue
  packages/components/skeleton-loader/src/skeleton-loader.ts
  packages/components/skeleton-loader/src/skeleton-loader.vue
  packages/components/skeleton-loader/stories/skeleton-loader-group.stories.ts
  packages/components/skeleton-loader/stories/skeleton-loader.stories.ts
  packages/components/skeleton-loader/style/css.ts
  packages/components/skeleton-loader/style/index.ts
  packages/components/skeleton-loader/test/skeleton-loader-group.spec.ts
  packages/components/skeleton-loader/test/skeleton-loader.spec.ts
  packages/locale/lang/en.ts
  packages/theme/src/index.scss
  packages/theme/src/skeleton-loader.scss
  typings/global.d.ts
Labels: Feature, waiting for UX, waiting for dev

#133 [Component] SpinnerLoader
  packages/components/index.ts
  packages/components/spinner-loader/index.ts
  packages/components/spinner-loader/src/spinner-loader.ts
  packages/components/spinner-loader/src/spinner-loader.vue
  packages/components/spinner-loader/stories/spinner-loader.stories.ts
  packages/components/spinner-loader/style/css.ts
  packages/components/spinner-loader/style/index.ts
  packages/components/spinner-loader/test/spinner-loader.spec.ts
  packages/puik/component.ts
  packages/theme/src/index.scss
  packages/theme/src/spinner-loader.scss
  pnpm-lock.yaml
  typings/global.d.ts
Labels: Feature, waiting for UX, waiting for dev

#126 [Docs]: improvements
  packages/components/accordion/stories/accordion-group.stories.ts
  packages/components/accordion/stories/accordion.stories.ts
  packages/components/alert/stories/alert.stories.ts
  packages/components/badge/stories/badge.stories.ts
  packages/components/breadcrumb/stories/breadcrumb.stories.ts
  packages/components/button-group/stories/button-group.stories.ts
  packages/components/button/stories/button.stories.ts
  packages/components/card/stories/card.stories.ts
  packages/components/checkbox/stories/checkbox.stories.ts
  packages/components/input/stories/input.stories.ts
  packages/components/link/stories/link.stories.ts
  packages/components/modal/stories/modal.stories.ts
  packages/components/progress-bar/stories/progress-bar.stories.ts
  packages/components/radio/stories/radio.stories.ts
  packages/components/select/stories/select.stories.ts
  packages/components/switch/stories/switch.stories.ts
  packages/components/tooltip/stories/tooltip.stories.ts
Labels: documentation
