Repository PrestaShopCorp/puik, pull requests merged in 2023-07, with the labels that each got.

#135 [Feat]: Table component
  packages/components/index.ts
  packages/components/table/index.ts
  packages/components/table/src/table.ts
  packages/components/table/src/table.vue
  packages/components/table/stories/table.stories.ts
  packages/components/table/style/css.ts
  packages/components/table/style/index.ts
  packages/components/table/test/table.spec.ts
  packages/locale/lang/en.ts
  packages/puik/component.ts
  packages/theme/src/index.scss
  packages/theme/src/table.scss
  typings/global.d.ts
Labels: Feature, WIP

#139 feat: add sidebar component, tests and docs
  packages/components/accordion/src/accordion.vue
  packages/components/index.ts
  packages/components/sidebar-group-item/style/css.ts
  packages/components/sidebar-group-item/style/index.ts
  packages/components/sidebar-item/style/css.ts
  packages/components/sidebar-item/style/index.ts
  packages/components/sidebar-title/style/css.ts
  packages/components/sidebar-title/style/index.ts
  packages/components/sidebar/index.ts
  packages/components/sidebar/src/sidebar-group-item.ts
  packages/components/sidebar/src/sidebar-group-item.vue
  packages/components/sidebar/src/sidebar-item.ts
  packages/components/sidebar/src/sidebar-item.vue
  packages/components/sidebar/src/sidebar-title.ts
  packages/components/sidebar/src/sidebar-title.vue
  packages/components/sidebar/src/sidebar.ts
  packages/components/sidebar/src/sidebar.vue
  packages/components/sidebar/stories/sidebar-group-item.stories.ts
  packages/components/sidebar/stories/sidebar-item.stories.ts
  packages/components/sidebar/stories/sidebar-title.stories.ts
  packages/components/sidebar/stories/sidebar.stories.ts
  packages/components/sidebar/style/css.ts
  packages/components/sidebar/style/index.ts
  packages/components/sidebar/test/sidebar-group-item.spec.ts
  packages/components/sidebar/test/sidebar-item.spec.ts
  packages/components/sidebar/test/sidebar-title.spec.ts
  packages/components/sidebar/test/sidebar.spec.ts
  packages/components/table/stories/table.stories.ts
  packages/locale/lang/en.ts
  packages/puik/component.ts
  packages/theme/src/accordion-group.scss
  packages/theme/src/index.scss
  packages/theme/src/sidebar-group-item.scss
  packages/theme/src/sidebar-item.scss
  packages/theme/src/sidebar-title.scss
  packages/theme/src/sidebar.scss
  typings/global.d.ts
Labels: waiting for UX, waiting for dev

#124 [Feat] Add test coverage
  .github/workflows/ci.yml
  CONTRIBUTING.md
  package.json
  packages/components/accordion/test/accordion-group.spec.ts
  packages/components/accordion/test/accordion.spec.ts
  packages/components/breadcrumb/test/breadcrumb.spec.ts
  pnpm-lock.yaml
  vitest.config.ts
Labels: Feature, waiting for dev
